?

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -28,134 +28,134 @@ jobs:
     with:
       release: true
 
-    release:
-      needs:
-        - matrix_prep
-        - build
-      runs-on: ubuntu-latest
+  release:
+    needs:
+      - matrix_prep
+      - build
+    runs-on: ubuntu-latest
 
-      permissions:
-        contents: write
+    permissions:
+      contents: write
 
-      strategy:
-        matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
+    strategy:
+      matrix: ${{ fromJson(needs.matrix_prep.outputs.matrix) }}
 
-      steps:
-        - uses: actions/checkout@v3
+    steps:
+      - uses: actions/checkout@v3
 
-        - name: Display context
-          run: |
-            echo ref_name = ${{ github.ref_name }}
-            echo target_release_tag = ${{ github.event.inputs.target_release_tag }}
+      - name: Display context
+        run: |
+          echo ref_name = ${{ github.ref_name }}
+          echo target_release_tag = ${{ github.event.inputs.target_release_tag }}
 
-        - name: Download build artifacts
-          uses: actions/download-artifact@v3
-          with:
-            name: build-artifacts
-            path: build-artifacts
+      - name: Download build artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: build-artifacts
+          path: build-artifacts
 
-        - name: Get github release information
-          if: ${{ github.event_name == 'workflow_dispatch' }}
-          id: get_release
-          uses: cardinalby/git-get-release-action@1.2.4
-          env:
-            GITHUB_TOKEN: ${{ github.token }}
-          with:
-            tag: ${{ github.event.inputs.target_release_tag }}
+      - name: Get github release information
+        if: ${{ github.event_name == 'workflow_dispatch' }}
+        id: get_release
+        uses: cardinalby/git-get-release-action@1.2.4
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        with:
+          tag: ${{ github.event.inputs.target_release_tag }}
 
-        - name: Generate publish related information
-          id: release_info
-          run: |
-            if [ $GITHUB_EVENT_NAME == 'release' ]
-            then
-                echo "tag_name=" >> $GITHUB_OUTPUT  # leave an empty value here so softprops/action-gh-release will use the default value
-            elif [ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]
-            then
-                echo "tag_name=${{ github.event.inputs.target_release_tag }}" >> $GITHUB_OUTPUT
-            else
-                echo Unknown github event name $GITHUB_EVENT_NAME
-                exit 1
-            fi
+      - name: Generate publish related information
+        id: release_info
+        run: |
+          if [ $GITHUB_EVENT_NAME == 'release' ]
+          then
+              echo "tag_name=" >> $GITHUB_OUTPUT  # leave an empty value here so softprops/action-gh-release will use the default value
+          elif [ $GITHUB_EVENT_NAME == 'workflow_dispatch' ]
+          then
+              echo "tag_name=${{ github.event.inputs.target_release_tag }}" >> $GITHUB_OUTPUT
+          else
+              echo Unknown github event name $GITHUB_EVENT_NAME
+              exit 1
+          fi
 
-        - name: Read common properties
-          id: properties_g
-          uses: christian-draeger/read-properties@1.1.1
-          with:
-            path: gradle.properties
-            properties: 'archives_name mod_version minecraft_version minecraft_supported_versions'
+      - name: Read common properties
+        id: properties_g
+        uses: christian-draeger/read-properties@1.1.1
+        with:
+          path: gradle.properties
+          properties: 'archives_name mod_version minecraft_version minecraft_supported_versions'
 
-        - name: Fix game version
-          id: game_versions
-          run: |
-            # Fixed \n in game_versions isn't parsed by christian-draeger/read-properties as a line separator
-            echo 'value<<EOF' >> $GITHUB_OUTPUT
-            echo -e "${{ steps.properties_v.outputs.minecraft_support_version }}" >> $GITHUB_OUTPUT
-            echo 'EOF' >> $GITHUB_OUTPUT
+      - name: Fix game version
+        id: game_versions
+        run: |
+          # Fixed \n in game_versions isn't parsed by christian-draeger/read-properties as a line separator
+          echo 'value<<EOF' >> $GITHUB_OUTPUT
+          echo -e "${{ steps.properties_v.outputs.minecraft_support_version }}" >> $GITHUB_OUTPUT
+          echo 'EOF' >> $GITHUB_OUTPUT
 
-        - name: Prepare file information
-          id: file_info
-          run: |
-            shopt -s extglob
-            FILE_PATHS=$(ls ${{ format('build-artifacts/{0}/build/libs/!(*-@(dev|sources|shadow)).jar', matrix.subproject) }})
-            if (( ${#FILE_PATHS[@]} != 1 )); then
-                echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
-                exit 1
-            else
-                FILE_PATH=${FILE_PATHS[0]}
-            fi
+      - name: Prepare file information
+        id: file_info
+        run: |
+          shopt -s extglob
+          FILE_PATHS=$(ls ${{ format('build-artifacts/{0}/build/libs/!(*-@(dev|sources|shadow)).jar', matrix.subproject) }})
+          if (( ${#FILE_PATHS[@]} != 1 )); then
+              echo "Error: Found ${#FILE_PATHS[@]} files, expected exactly 1"
+              exit 1
+          else
+              FILE_PATH=${FILE_PATHS[0]}
+          fi
+          
+          FILE_NAME=$(basename $FILE_PATH)
+          FILE_HASH=$(sha256sum $FILE_PATH | awk '{ print $1 }')
+          echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
+          echo "name=$FILE_NAME" >> $GITHUB_OUTPUT
+          echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
+          cat $GITHUB_OUTPUT
+
+      - name: Prepare changelog
+        uses: actions/github-script@v6
+        id: changelog
+        with:
+          script: return process.env.CHANGELOG
+          result-encoding: string
+        env:
+          CHANGELOG: |-
+            ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
             
-            FILE_NAME=$(basename $FILE_PATH)
-            FILE_HASH=$(sha256sum $FILE_PATH | awk '{ print $1 }')
-            echo "path=$FILE_PATH" >> $GITHUB_OUTPUT
-            echo "name=$FILE_NAME" >> $GITHUB_OUTPUT
-            echo "hash=$FILE_HASH" >> $GITHUB_OUTPUT
-            cat $GITHUB_OUTPUT
+            -------
+            
+            Build Information
+            
+            - File name: `${{ steps.file_info.outputs.name }}`
+            - SHA-256: `${{ steps.file_info.outputs.hash }}`
+            - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
 
-        - name: Prepare changelog
-          uses: actions/github-script@v6
-          id: changelog
-          with:
-            script: return process.env.CHANGELOG
-            result-encoding: string
-          env:
-            CHANGELOG: |-
-              ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
-              
-              -------
-              
-              Build Information
-              
-              - File name: `${{ steps.file_info.outputs.name }}`
-              - SHA-256: `${{ steps.file_info.outputs.hash }}`
-              - Built from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+      - name: Publish Minecraft Mods
+        uses: Kir-Antipov/mc-publish@v3.3
+        with:
+          modrinth-id: DgWBIBY5  # https://modrinth.com/mod/quickbackupmulti
+          modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}
 
-        - name: Publish Minecraft Mods
-          uses: Kir-Antipov/mc-publish@v3.3
-          with:
-            modrinth-id: DgWBIBY5  # https://modrinth.com/mod/quickbackupmulti
-            modrinth-token: ${{ secrets.MODRINTH_API_TOKEN }}
+          curseforge-id: 951047 # https://www.curseforge.com/minecraft/mc-mods/quickbackupmulti
+          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
 
-            curseforge-id: 951047 # https://www.curseforge.com/minecraft/mc-mods/quickbackupmulti
-            curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
+          github-tag: ${{ steps.release_info.outputs.tag_name }}
+          github-token: ${{ secrets.GITHUB_TOKEN }}
 
-            github-tag: ${{ steps.release_info.outputs.tag_name }}
-            github-token: ${{ secrets.GITHUB_TOKEN }}
+          files: ${{ steps.file_info.outputs.path }}
 
-            files: ${{ steps.file_info.outputs.path }}
+          name: ${{ format('{0} v{1} for mc{2}', steps.properties_g.outputs.archives_name, steps.properties_g.outputs.mod_version, steps.properties_v.outputs.minecraft_version) }}
+          version: ${{ format('mc{0}-v{1}', steps.properties_v.outputs.minecraft_version, steps.properties_g.outputs.mod_version) }}
+          version-type: release
 
-            name: ${{ format('{0} v{1} for mc{2}', steps.properties_g.outputs.archives_name, steps.properties_g.outputs.mod_version, steps.properties_v.outputs.minecraft_version) }}
-            version: ${{ format('mc{0}-v{1}', steps.properties_v.outputs.minecraft_version, steps.properties_g.outputs.mod_version) }}
-            version-type: release
+          loaders: |
+            fabric
+            neoforge
+          game-versions: ${{ steps.game_versions.outputs.value }}
+          game-version-filter: any
 
-            loaders: |
-              fabric
-              neoforge
-            game-versions: ${{ steps.game_versions.outputs.value }}
-            game-version-filter: any
+          github-changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
+          modrinth-changelog: ${{ steps.changelog.outputs.result }}
+          curseforge-changelog: ${{ steps.changelog.outputs.result }}
 
-            github-changelog: ${{ format('{0}{1}', github.event.release.body, steps.get_release.outputs.body) }}
-            modrinth-changelog: ${{ steps.changelog.outputs.result }}
-            curseforge-changelog: ${{ steps.changelog.outputs.result }}
-
-            retry-attempts: 3
-            retry-delay: 10000
+          retry-attempts: 3
+          retry-delay: 10000
